FORMAT: 1A
HOST: http://backend.helloworld.nader.tech

# Hello World API

<!-- include(../../src/module/auth/auth.apib) -->

<!-- include(../../src/module/self/self.apib) -->

<!-- include(../../src/module/post/post.apib) -->

<!-- include(./draft.apib) -->
